### PR TITLE
Using boxes/scores/labels from pipeline instead of predictions

### PR DESCRIPTION
**Pull request by corey-nm**
Testing plan: *needs testing!!!*

### CODE REVIEW

**Comment by corey-nm** [comment]
@KSGulin any updates on this one?

**Review by bfineran — APPROVED** [review]
LGTM pending test

**Review by KSGulin — APPROVED** [review]

**Review by KSGulin — CHANGES_REQUESTED** [review]
Approved incorrectly previously, as there are still errors

**Review by KSGulin — APPROVED** [review]
Passed local test. Great stuff

**Review by rahul-tuli — APPROVED** [review]

**Pull request merged**
